ipc2: ipc030 ipc046
	@clear
	@echo "========"
	@echo " ipc030 "
	@echo "========"
	@echo "        "
	@./ipc030
	@echo "        "
	@echo "========"
	@echo " ipc046 "
	@echo "========"
	@echo "        "
	@./ipc046

ipc030:
	gcc ipc030.c -o ipc030

ipc046:
	gcc ipc046.c -o ipc046

clean:
	rm -f ipc030 ipc046 *~
