mem: mem08 mem10
	@clear
	@echo "========"
	@echo " mem08 "
	@echo "========"
	@echo "        "
	@./mem08
	@echo "        "
	@echo "========"
	@echo " mem10 "
	@echo "========"
	@echo "        "
	@./mem10

mem08: mem08.c
	gcc mem08.c -o mem08

mem10: mem10.c
	gcc mem10.c -o mem10

clean:
	rm -f mem08 mem10 *~
